# Generated by Django 3.0.4 on 2020-03-29 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.AutoField(db_column='idClient', primary_key=True, serialize=False)),
                ('clienfirstname_ar', models.CharField(db_column='ClienFirstname_Ar', max_length=45)),
                ('lastname_ar', models.CharField(db_column='LastName_Ar', max_length=45)),
                ('firstname_fr', models.CharField(db_column='Firstname_Fr', max_length=45)),
                ('lastname_fr', models.CharField(db_column='LastName_Fr', max_length=45)),
                ('passeport_id', models.CharField(blank=True, db_column='Passeport_id', max_length=45, null=True, unique=True)),
                ('telephonenb', models.IntegerField(db_column='TelephoneNb')),
                ('e_mail_fabebook', models.CharField(db_column='E-mail/Fabebook', max_length=45, unique=True)),
                ('date_place_of_birth', models.CharField(db_column='Date/Place_of_Birth', max_length=45)),
                ('user_iduser', models.ForeignKey(db_column='User_idUser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client',
                'managed': True,
                'unique_together': {('idclient', 'user_iduser')},
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insurance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Omra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_field', models.IntegerField(blank=True, db_column='food?', null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=45, null=True)),
                ('area', models.CharField(blank=True, max_length=45, null=True)),
                ('distance_from_haram', models.IntegerField(blank=True, null=True)),
                ('room_size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'omra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizedJourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('room_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organized_journey',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'other',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TempHotelReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'temp_hotel_reservation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TempTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'temp_ticket',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(max_length=11)),
                ('number', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'ticket',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TravelHotelReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'travel_hotel_reservation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('single_voyage_field', models.IntegerField(blank=True, db_column='single_voyage?', null=True)),
            ],
            options={
                'db_table': 'visa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VisaRdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'visa_rdv',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VisaRequestForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'visa_request_form',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.IntegerField(blank=True, null=True)),
                ('client', models.ManyToManyField(to='home.Client')),
                ('insurance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Insurance')),
                ('omra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Omra')),
                ('organized_journey', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='home.OrganizedJourney')),
                ('other', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Other')),
                ('temp_hotel_reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.TempHotelReservation')),
                ('temp_ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.TempTicket')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Ticket')),
                ('travel_hotel_reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.TravelHotelReservation')),
                ('user_iduser', models.ForeignKey(db_column='User_idUser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('visa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Visa')),
                ('visa_rdv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.VisaRdv')),
                ('visa_request_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.VisaRequestForm')),
            ],
            options={
                'db_table': 'service',
                'managed': True,
                'unique_together': {('id', 'user_iduser')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.AutoField(db_column='Id_Payment', primary_key=True, serialize=False)),
                ('sum_payment', models.IntegerField()),
                ('date', models.DateField()),
                ('id_service', models.ForeignKey(db_column='id_service', on_delete=django.db.models.deletion.DO_NOTHING, to='home.Service')),
                ('user_iduser', models.ForeignKey(db_column='User_idUser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
                'unique_together': {('id_payment', 'id_service', 'user_iduser')},
            },
        ),
        migrations.CreateModel(
            name='CancelService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('id_service', models.ForeignKey(db_column='id_service', on_delete=django.db.models.deletion.DO_NOTHING, to='home.Service')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cancel_service',
                'managed': True,
                'unique_together': {('id', 'id_service', 'id_user')},
            },
        ),
        migrations.CreateModel(
            name='CancelPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='Date')),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('id_payment', models.ForeignKey(db_column='id_payment', on_delete=django.db.models.deletion.DO_NOTHING, to='home.Payment')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cancel_payment',
                'managed': True,
                'unique_together': {('id', 'id_user', 'id_payment')},
            },
        ),
    ]
