# Generated by Django 3.0.4 on 2020-08-27 18:18

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cancel_service',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.AutoField(db_column='idClient', primary_key=True, serialize=False)),
                ('name_ar', models.CharField(db_column='name_ar', max_length=90)),
                ('name_fr', models.CharField(db_column='name_fr', max_length=90)),
                ('passeport_id', models.CharField(blank=True, db_column='Passeport_id', max_length=45, null=True, unique=True)),
                ('telephonenb', models.PositiveIntegerField(db_column='TelephoneNb')),
                ('e_mail_fabebook', models.CharField(db_column='E-mail/Fabebook', max_length=45, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_countries.fields.CountryField(max_length=2)),
                ('visa_rdv', models.BooleanField(blank=True, default=False, null=True)),
                ('visa', models.BooleanField(blank=True, default=False, null=True)),
                ('organized_trip', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('facebook', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Service', models.CharField(max_length=45)),
                ('inquirycol', models.CharField(max_length=50)),
                ('answered', models.BooleanField(blank=True, default=False, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inquiry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'insurance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Omra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_field', models.BooleanField(blank=True, default=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=45, null=True)),
                ('area', models.CharField(blank=True, max_length=45, null=True)),
                ('distance_from_haram', models.PositiveIntegerField(blank=True, null=True)),
                ('room_size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'omra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizedJourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('room_type', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'organized_journey',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'other',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('ADTK', 'حجز تذكـرة'), ('CHTK', 'تغيير تذكـرة')], default='ADTK', max_length=45)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ticket',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TravelHotelReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('City', models.CharField(max_length=45)),
                ('reservation_number', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'travel_hotel_reservation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('single_voyage_field', models.PositiveIntegerField(blank=True, db_column='single_voyage?', null=True)),
                ('country', django_countries.fields.CountryField(default='PS', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'visa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('temp_ticket', models.BooleanField(blank=True, null=True)),
                ('temp_hotel_reservation', models.CharField(choices=[('voucher', 'فاتورة'), ('normal', 'عادي')], default='normal', max_length=45)),
                ('visa_rdv', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('visa_request_form', models.BooleanField(blank=True, null=True)),
                ('main_price', models.FloatField(blank=True, null=True)),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ManyToManyField(to='home.Client')),
                ('insurance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Insurance')),
                ('omra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Omra')),
                ('organized_journey', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.OrganizedJourney')),
                ('other', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Other')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Ticket')),
                ('travel_hotel_reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.TravelHotelReservation')),
                ('user_iduser', models.ForeignKey(db_column='User_idUser', default=crum.get_current_user, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('visa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Visa')),
            ],
            options={
                'db_table': 'service',
                'managed': True,
                'unique_together': {('id', 'user_iduser')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('visa_rdv', models.BooleanField(blank=True, default=False, null=True)),
                ('visa', models.BooleanField(blank=True, default=False, null=True)),
                ('organized_trip', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Country')),
            ],
            options={
                'db_table': 'Region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cancel_service_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.CancelService')),
            ],
            options={
                'db_table': 'refund',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('visa_rdv', models.BooleanField(blank=True, default=False, null=True)),
                ('visa', models.BooleanField(blank=True, default=False, null=True)),
                ('organized_trip', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Region')),
            ],
            options={
                'db_table': 'City',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cancelservice',
            name='id_service',
            field=models.ForeignKey(db_column='id_service', on_delete=django.db.models.deletion.DO_NOTHING, to='home.Service'),
        ),
        migrations.AddField(
            model_name='cancelservice',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.AutoField(db_column='Id_Payment', primary_key=True, serialize=False)),
                ('sum_payment', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('id_service', models.ForeignKey(db_column='id_service', on_delete=django.db.models.deletion.DO_NOTHING, to='home.Service')),
                ('user_iduser', models.ForeignKey(db_column='User_idUser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
                'unique_together': {('id_payment', 'id_service', 'user_iduser')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cancelservice',
            unique_together={('id', 'id_service', 'id_user')},
        ),
    ]
