# Generated by Django 3.0.4 on 2020-08-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_payment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='country',
        ),
    ]
