# Generated by Django 3.0.4 on 2020-03-29 06:51

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200329_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelhotelreservation',
            name='country',
            field=django_countries.fields.CountryField(default='NZ', max_length=2),
        ),
    ]
