# Generated by Django 3.0.4 on 2020-03-29 07:14

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_travelhotelreservation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelhotelreservation',
            name='City',
            field=models.CharField(blank=True, default='dddd', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='visa',
            name='country',
            field=django_countries.fields.CountryField(default='PS', max_length=2),
        ),
        migrations.AlterField(
            model_name='travelhotelreservation',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='PS', max_length=2, null=True),
        ),
    ]
