# Generated by Django 3.0.4 on 2020-08-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_service_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='telephonenb',
        ),
        migrations.AddField(
            model_name='client',
            name='telephone_nb',
            field=models.CharField(db_column='TelephoneNb', default=None, max_length=45),
        ),
    ]
