# Generated by Django 3.0.4 on 2020-03-29 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200329_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='visa_rdv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='visa_request_form',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelhotelreservation',
            name='City',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='travelhotelreservation',
            name='country',
            field=django_countries.fields.CountryField(default=datetime.datetime(2020, 3, 29, 7, 20, 6, 122052, tzinfo=utc), max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VisaRdv',
        ),
        migrations.DeleteModel(
            name='VisaRequestForm',
        ),
    ]
