# Generated by Django 3.0.4 on 2020-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200828_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omra',
            name='food_field',
        ),
        migrations.AddField(
            model_name='omra',
            name='food',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
