# Generated by Django 3.0.4 on 2020-03-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200329_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client',
        ),
    ]
