# Generated by Django 3.0.4 on 2020-08-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200828_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='passeport_id',
            new_name='passport_id',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='telephone_nb',
            new_name='telephone',
        ),
        migrations.AlterField(
            model_name='omra',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizedjourney',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
