# Generated by Django 3.0.4 on 2020-08-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200828_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='organized_journey',
            new_name='organized_trip',
        ),
    ]
