# Generated by Django 3.0.4 on 2020-03-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_service_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ManyToManyField(to='home.Client'),
        ),
    ]
