# Generated by Django 3.0.4 on 2020-03-29 07:40

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_service_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='country',
            field=django_countries.fields.CountryField(default=datetime.datetime(2020, 3, 29, 7, 40, 24, 318238, tzinfo=utc), max_length=2),
            preserve_default=False,
        ),
    ]
