# Generated by Django 3.0.4 on 2020-08-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200829_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visa',
            old_name='single_voyage_field',
            new_name='single_visit',
        ),
    ]
