# Generated by Django 3.0.4 on 2020-03-29 08:16

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200329_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizedjourney',
            name='country',
            field=django_countries.fields.CountryField(default=datetime.datetime(2020, 3, 29, 8, 16, 33, 518628, tzinfo=utc), max_length=2),
            preserve_default=False,
        ),
    ]
