# Generated by Django 3.0.4 on 2020-03-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_organizedjourney_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omra',
            name='food_field',
            field=models.CharField(blank=True, choices=[('WF', 'برنامج عمرة مع الأكل'), ('WIF', 'برنامج عمرة بدون الأكل')], max_length=45, null=True),
        ),
    ]
