# Generated by Django 3.0.4 on 2020-08-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200829_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='single_visit',
            field=models.BooleanField(default=True),
        ),
    ]
