# Generated by Django 3.0.4 on 2020-03-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200329_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omra',
            name='food_field',
            field=models.CharField(blank=True, choices=[('WF', 'برنامج عمرة مع الأكل'), ('WIF', 'برنامج عمرة بدون الأكل')], default='WF', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_of',
            field=models.CharField(choices=[('ADTK', 'حجز تذكـرة'), ('CHTK', 'تغيير تذكـرة')], default='ADTK', max_length=45),
        ),
    ]
