# Generated by Django 3.0.4 on 2020-03-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200329_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('cancel_service_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.CancelService')),
            ],
            options={
                'db_table': 'refund',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='CancelPayment',
        ),
    ]
