# Generated by Django 3.0.4 on 2020-03-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200329_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelservice',
            name='penalty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
