# Generated by Django 3.0.4 on 2020-03-29 14:57

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_cancelservice_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('facebook', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Service', models.CharField(max_length=45)),
                ('inquirycol', models.CharField(max_length=50)),
                ('answered', models.BooleanField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inquiry',
                'managed': True,
            },
        ),
    ]
