# Generated by Django 3.0.4 on 2020-08-27 10:05

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0019_auto_20200402_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('visa_rdv', models.BooleanField(default=False)),
                ('visa', models.BooleanField(default=False)),
                ('organized_trip', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'City',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('visa_rdv', models.BooleanField(default=False)),
                ('visa', models.BooleanField(default=False)),
                ('organized_trip', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('visa_rdv', models.BooleanField(default=False)),
                ('visa', models.BooleanField(default=False)),
                ('organized_trip', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Region',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='organized_journey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.OrganizedJourney'),
        ),
        migrations.AlterField(
            model_name='service',
            name='user_iduser',
            field=models.ForeignKey(db_column='User_idUser', default=crum.get_current_user, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='visa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Visa'),
        ),
    ]
